### ISSUE TITLE
[FEA] Fix GetJsonObject

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#10254]
This is an epic to fix all of the bugs with GetJsonObject, and see if there are any more that we can find.

  * [ ] https://github.com/NVIDIA/spark-rapids/issues/10226 
  * [ ] https://github.com/NVIDIA/spark-rapids/issues/10219 
  * [ ] https://github.com/NVIDIA/spark-rapids/issues/10218 
  * [ ] https://github.com/NVIDIA/spark-rapids/issues/10217 
  * [ ] https://github.com/NVIDIA/spark-rapids/issues/10216 
  * [ ] https://github.com/NVIDIA/spark-rapids/issues/10215 
  * [ ] https://github.com/NVIDIA/spark-rapids/issues/10214 
  * [ ] https://github.com/NVIDIA/spark-rapids/issues/10213 
  * [ ] https://github.com/NVIDIA/spark-rapids/issues/10212 
  * [ ] https://github.com/NVIDIA/spark-rapids/issues/10196 
  * [ ] https://github.com/NVIDIA/spark-rapids/issues/10194 
  * [ ] https://github.com/NVIDIA/spark-rapids/issues/9033

**Comment by res-life** [comment]
Verified the following issues successfully against unmerged [PR](https://github.com/NVIDIA/spark-rapids-jni/pull/1868):   
https://github.com/NVIDIA/spark-rapids/issues/10537
https://github.com/NVIDIA/spark-rapids/issues/10217
https://github.com/NVIDIA/spark-rapids/issues/10216
https://github.com/NVIDIA/spark-rapids/issues/10196
https://github.com/NVIDIA/spark-rapids/issues/10194
https://github.com/NVIDIA/spark-rapids/issues/9033

https://github.com/NVIDIA/spark-rapids/issues/10218:  3/4 pass 1/4 fail, haoyang will fix
https://github.com/NVIDIA/spark-rapids/issues/10212:  Haoyang will fix in [Plugin PR](https://github.com/NVIDIA/spark-rapids/pull/10581)

**Comment by res-life** [comment]
1. **#10194, #10196, #10537, #10217, #10216, #9033** 

     Will be fixed by PRs:
- JNI PR: https://github.com/NVIDIA/spark-rapids-jni/pull/1893
- https://github.com/NVIDIA/spark-rapids/pull/10581

2. #10212 
will be fixed, @thirtiseven please double confirm.

3. And for #10218, 3/4 sub-items are done, and sub-item number normalization is postphoned.

4. For testing #10226 
    did not plan in Release 24.04.
