### ISSUE TITLE
[FEA] Fully support StructToJson/to_json

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#10594]
**Is your feature request related to a problem? Please describe.**
We have gotten a lot done on to_json, but there is still more that needs to be done.

Higher Priority:
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10478
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10477
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10371
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10316 includes from_json too

Low Priority:
- [ ] https://github.com/NVIDIA/spark-rapids/issues/9602
- [ ] https://github.com/NVIDIA/spark-rapids/issues/9517
