### ISSUE TITLE
[FEA] Add support for Databricks 14.3 ML LTS

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#10661]
**Is your feature request related to a problem? Please describe.**
Add support to the plugin for [Databricks 14.3 ML LTS](https://docs.databricks.com/en/release-notes/runtime/14.3lts-ml.html)

**Describe the solution you'd like**
Add a shim layer for Databricks 14.3 (Spark 3.5.0)

**Describe alternatives you've considered**
N/A

**Additional context**

### Issues affecting Databricks 14.3 even without Delta Lake and Deletion Vectors

- [x] #12096 
- [x] https://github.com/NVIDIA/spark-rapids/issues/12087
- [x] https://github.com/NVIDIA/spark-rapids/issues/11988
- [x] https://github.com/NVIDIA/spark-rapids/issues/12020
- [x] https://github.com/NVIDIA/spark-rapids/issues/11990

### Issues needed for basic Delta Lake support without Deletion Vectors

- [x] https://github.com/NVIDIA/spark-rapids/issues/12056
- [x] https://github.com/NVIDIA/spark-rapids/issues/12047

### Issues pertaining to Deletion Vectors Read Support 

- [ ] https://github.com/NVIDIA/spark-rapids/issues/12070
- [ ] #12341
- [ ] https://github.com/NVIDIA/spark-rapids/issues/12071
- [ ] https://github.com/NVIDIA/spark-rapids/issues/12072
- [ ] https://github.com/NVIDIA/spark-rapids/issues/12073
- [ ] https://github.com/NVIDIA/spark-rapids/issues/11541

### Issues pertaining to Deletion Vectors Write Support 

- [ ] https://github.com/NVIDIA/spark-rapids/issues/12027
- [ ] https://github.com/NVIDIA/spark-rapids/issues/12041

### Low Priority Issues

- [ ] https://github.com/NVIDIA/spark-rapids/issues/11711
- [ ] https://github.com/NVIDIA/spark-rapids/issues/11902

**Comment by liurenjie1024** [comment]
I'll take this.

**Comment by mythrocks** [comment]
I've added https://github.com/NVIDIA/spark-rapids/issues/10969 to this task list.  This might not be a deal breaker for Databricks 14.3, really.  But I'm adding it here for tracking.
