### ISSUE TITLE
[FEA] Run Spark UT with spark-rapids

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#10744]
**Is your feature request related to a problem? Please describe.**
Run the Spark UT with enabling spark-rapids to verify the correctness of features as many as possible.
The test cases are in https://github.com/apache/spark/tree/master/sql/.

There may be different Suite code in different Spark versions. It means we need to push different test code to shims.
And we can focus on Spark 3.3.0 as the first step.

Here're some Suite we may begin from
- [x] #10745
- [x] ./catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/MathExpressionsSuite.scala
- [x] ./catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/RegexpExpressionsSuite.scala
- [x] ./core/src/test/scala/org/apache/spark/sql/StringFunctionsSuite.scala
- [x] ./core/src/test/scala/org/apache/spark/sql/JsonFunctionsSuite.scala
- [x] ./catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/JsonExpressionsSuite.scala
- [x] ./core/src/test/scala/org/apache/spark/sql/execution/datasources/json/JsonSuite.scala
- [ ] To add more

**Comment by binmahone** [comment]
closed by https://github.com/NVIDIA/spark-rapids/pull/10743
