### ISSUE TITLE
[BUG] Issues found by Spark UT Framework on RapidsJsonExpressionsSuite

### ISSUE THREAD

**Issue by binmahone** [NVIDIA/spark-rapids#10849]
**Describe the bug**

Spark UT Framework enabled RapidsJsonExpressionsSuite(https://github.com/NVIDIA/spark-rapids/pull/10851) with the following test cases explicitly excluded:

- [ ] from_json - invalid data  
     https://github.com/NVIDIA/spark-rapids/issues/10891
- [x] from_json - input=empty array, schema=struct, output=single row with null
   #10907
- [x] from_json - input=empty object, schema=struct, output=single row with null 
   #10910
- [x] SPARK-20549: from_json bad UTF-8 
   #10911
- [x] from_json with timestamp
- [x] to_json - array 
   #10915
- [x] to_json - empty array
    #10924
- [x] to_json - array with single empty row 
    #10923
- [x] to_json with timestamp
- [x] SPARK-21513: to_json support map[string, struct] to json  
    #10916
- [ ] ** SPARK-21513: to_json support map[struct, struct] to json
    #10918
- [x]  SPARK-21513: to_json support map[string, integer] to json 
    #10919
- [x] to_json - array with maps 
    #10920
- [x] to_json - array with a single map 
    #10921
- [x] from_json missing fields 
    #10922

**These excluded test cases needs further investigating!!!**
Notice: Other test cases in this suite may pass with falling back!

**Steps/Code to reproduce bug**
1. Compile everything with `mvn -Dbuildver=330 install -DskipTests`
2. Pick a test case name in the above table
3. Go to RapidsTestSettings and find the line starting with ".exclude" and containing the test case name, comment it out
4. Run the Suite then you'll see one failed test case. E.g. `mvn -nsu -Dbuildver=330 -pl tests -Dsuites="org.apache.spark.sql.rapids.suites.RapidsXXXSuite" test` (replace RapidsXXXSuite with the right name in issue header). ALWAYS double check if your suite name coincide with in source code, as it may contain typos!

**Expected behavior**
The suite can pass without excluding any test case.
