### ISSUE TITLE
[FEA] Implement low shuffle merge

### ISSUE THREAD

**Issue by liurenjie1024** [NVIDIA/spark-rapids#10904]
**Is your feature request related to a problem? Please describe.**
Implement low shuffle merge optimization to improve merge performance.

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10905
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10906
- [ ] https://github.com/NVIDIA/spark-rapids/issues/11077
- [ ] https://github.com/NVIDIA/spark-rapids/issues/11078
- [ ] https://github.com/NVIDIA/spark-rapids/issues/11079
- [ ] https://github.com/NVIDIA/spark-rapids/issues/11095
- [ ] https://github.com/NVIDIA/spark-rapids/issues/11125
```
