### ISSUE TITLE
Revisit the ANSI tests which is enabled by default in Spark 4.0.0

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#11047]
As part of adding support for Spark 4.0.0 we explicitly set the `spark.sql.ansi.enabled` to false. This helped us to quickly pass the tests but we need to revisit each and every test and make sure we test against ANSI turned on. 
```[tasklist]
### Tasks
- [ ] Find all test cases where operators include ANSI
- [ ] Add corresponding tests for enabling ANSI
- [ ] [P1] For operators that we don't think include ANSI, have an option to run those with ANSI enabled
```

**Comment by nartal1** [comment]
Closing this as duplicate of https://github.com/NVIDIA/spark-rapids/issues/11106
