### ISSUE TITLE
[BUG] Revisit integration tests with @disable_ansi_mode label

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#11106]
As part of #9259 and #11004, we added support for Spark 4.0.0 but had to switch ANSI mode from the default `true` to `false` for many of our tests to pass. 

We should revisit our test suite and add ANSI tests for cases where we aren't covered. 

* [x] **arithmetic_test.py** -  We have separate tests for ansi mode tests.
* [x] **map_test.py** -  No changes required, the tests should be disabled for ansi mode as we have coverage for failures in other tests.
* [x] **get_json_test.py** - https://github.com/NVIDIA/spark-rapids/issues/11130
* [x] **window_function_test.py** - https://github.com/NVIDIA/spark-rapids/pull/13032
* [x] **hash_aggregate_test.py**  - https://github.com/NVIDIA/spark-rapids/pull/13032
* [x] **date_time_test.py** - No changes required, the tests should be disabled for ansi mode as we have coverage for failures in other tests.
* [x] **ast_test.py** - No changes required, the tests should be disabled for ansi mode as we have coverage for failures in other tests(subtraction -overflow when ansi is enabled).
* [x] **dpp_test.py**  - Should remove the **label** as the tests pass now after ansi support for SUM aggregate was added.
* [x] **grouping_sets_test.py** - Should remove the **label** as the tests pass now after ansi support for SUM aggregate was added.
* [x] **conditionals_test.py** - We need to disable ansi mode in some cases.
* [x] **cache_test.py** - Should remove the **label** for all the tests except one - https://github.com/NVIDIA/spark-rapids/issues/12700
* [x] **aqe_test.py** - enable tests which has hashaggregate operator.
* [x] **parquet_test.py** - enable tests which has hashAggregate operator, disable one that is due to overflow error. We have that test covered. So should be fine.
* [x] **qa_nightly_select_test.py** - We need to disable ansi mode for some cases. Those are already tested with ansi mode in other tests.
* [x] **url_test.py** - https://github.com/NVIDIA/spark-rapids/issues/12941
* [x] **string_test.py** - No changes required, the test should be disabled in ansi mode.
* [x] **cast_test.py** - No changes required, the tests should be disabled in ansi mode.
* [x] **join_test.py** - enable some of the tests which has aggregates, 
* [x] **json_test.py** - https://github.com/NVIDIA/spark-rapids/issues/12941, https://github.com/NVIDIA/spark-rapids/issues/12943
* [x] **date_time_test.py** - No changes required. According to PR, we should disable ansi for those tests.
* [x] **json_matrix_test.py** - P1 bug - https://github.com/NVIDIA/spark-rapids/issues/11154
