### ISSUE TITLE
[FEA] [EPIC] Add support for kudo shuffle serialization format.

### ISSUE THREAD

**Issue by liurenjie1024** [NVIDIA/spark-rapids#11590]
We have implemented kudo shuffle format, which significantly reduced serialization/deserialization time during shuffle comprared with current jcudf serialization format for wide tables.

TODOs

- [ ] 1. [Introduce Kudo shuffle format. #2496](https://github.com/NVIDIA/spark-rapids-jni/issues/2496)
- [x] 2. Code refactor for the preparation to add in the Kudo in Plugin. (https://github.com/NVIDIA/spark-rapids/pull/11667)
- [ ] 3. Enable Kudo in Plugin for shuffle and sized hash join (https://github.com/NVIDIA/spark-rapids/pull/11724)
