### ISSUE TITLE
[FEA] enable from_json and json scan by default

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#11630]
**Is your feature request related to a problem? Please describe.**
We will not be perfect in everything that we do, but we should be close enough that that we can enable most of from_json and json scan by default. There are still outstanding issues that prevent us from enabling all config options and all data types in all versions of Spark. There are also some odd corner cases that we need to at least document how we are different. We should also provide some configs to enable and disable data types individually. 

Things that must be fixed before we can enable from_json and json scan by default
  * [x] https://github.com/NVIDIA/spark-rapids/issues/10483 (I think this is done but I need to go over the tests again to be sure that it is)
  * [x] https://github.com/NVIDIA/spark-rapids/issues/10489 (I think this is done but I need to go over the tests again to be sure that it is)
  * [x] https://github.com/rapidsai/cudf/issues/16999
  * [x] https://github.com/rapidsai/cudf/issues/17261

Types that we do not support by default:
   * [ ] Top level arrays are not supported
   * [ ] Top level Maps should still be off by default
   * [ ] Dates
       * [ ] https://github.com/NVIDIA/spark-rapids/issues/6846
       * [ ] https://github.com/NVIDIA/spark-rapids/issues/10535
       * [ ] https://github.com/NVIDIA/spark-rapids/issues/11391
       * [ ] https://github.com/NVIDIA/spark-rapids/issues/4940
       * [ ] https://github.com/NVIDIA/spark-rapids/issues/9664
       * [ ] https://github.com/NVIDIA/spark-rapids/issues/9724
   * [ ] Timestamps
       * [ ] https://github.com/NVIDIA/spark-rapids/issues/6846 
       * [ ] https://github.com/NVIDIA/spark-rapids/issues/10535
       * [ ] https://github.com/NVIDIA/spark-rapids/issues/11391
       * [ ] https://github.com/NVIDIA/spark-rapids/issues/4940
       * [ ] https://github.com/NVIDIA/spark-rapids/issues/9664
       * [ ] https://github.com/NVIDIA/spark-rapids/issues/9724

Configs that we do not support by default:
  * [ ] non-UTC time zones if a timestamp or date type is present. (https://github.com/NVIDIA/spark-rapids/issues/10453)
  * [ ] non-default timestampFormat/dateFormat if a timestamp or date type is present (https://github.com/NVIDIA/spark-rapids/issues/10485)

Things that must be documented as corner cases:
  * [ ] Numbers are not normalized like they are in Spark or even like they are in get_json_object when read as a string
      * [ ] https://github.com/rapidsai/cudf/issues/15318
      * [ ] https://github.com/NVIDIA/spark-rapids/issues/10574
  * [ ] allowNonNumericNumbers matches later versions of Spark when validating results (https://github.com/NVIDIA/spark-rapids/issues/10493)
  * [ ] A double " inside a single quoted string is handled correctly by the RAPIDS Accelerator, but incorrectly by versions of Spark before 3.3.0 (https://github.com/NVIDIA/spark-rapids/issues/10495)
  * [ ] The RAPIDS Accelerator does not handle parsing non-arabic number in quoted strings (https://github.com/NVIDIA/spark-rapids/issues/10532)
  * [ ] non-top level arrays with numeric values that overflow produce different results (https://github.com/NVIDIA/spark-rapids/issues/10573, https://github.com/NVIDIA/spark-rapids/issues/11491)
  * [ ] non-top level structs/objects with numeric values that overflow produce different results on Spark 3.4.1 and below (https://github.com/NVIDIA/spark-rapids/issues/10588)
  * [ ] duplicate named values in an array are not handled the same as spark (https://github.com/NVIDIA/spark-rapids/issues/11361)
  * [ ] Spark 3.2.X will parse quoted integers, but the RPAIDS accelerator follows later versions of Spark (https://github.com/NVIDIA/spark-rapids/issues/11390, https://issues.apache.org/jira/browse/SPARK-38060)
  * [ ] https://github.com/NVIDIA/spark-rapids/issues/11632
  * [ ] https://github.com/rapidsai/cudf/issues/17349
