### ISSUE TITLE
[FEA] Decimal support for multiply int div, add, subtract and null safe equals

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#1329]
**Is your feature request related to a problem? Please describe.**
We support a few binary ops for decimal, like comparisons, but we should look into support for the others that we support.

Specifically 
 - [x] multiply 
 - [x] integral divide 
 - [x] subtract
 - [x] add 

Next priority is 
 - [x] EqualsNullSafe (again follow on issue if this is not supported right now)

This will also require us to support `PromotePrecision` (which is just metadata and a noop is OK) and `CheckOverflow` (which for the most part this should be fine for binary ops, but we need to check that it is OK for other operations where it might be inserted)
  - [x] PromotePrecition #976
  - [x] CheckOverflow #976

The following will be done as a part of a follow on issue #1572 
 - [ ] pmod - cudf issue: https://github.com/rapidsai/cudf/issues/7132
 - [ ] remainder - cudf issue: https://github.com/rapidsai/cudf/issues/7132
 - [ ] divide - - cudf issue: https://github.com/rapidsai/cudf/issues/7132

**Comment by rwlee** [comment]
Starting with decimal support for add.
