### ISSUE TITLE
[FEA] Execute UDFs that provide a RAPIDS execution path

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1351]
**Is your feature request related to a problem? Please describe.**
Some users may wish to provide a UDF that has both a CPU and a GPU implementation, the latter executing directly on the RAPIDS cudf `ColumnVector` instances just as the plugin operators do.  This has a significant drawback in that the user has to implement the UDF twice, but it should provide the best performance when running with the RAPIDS Accelerator.

**Describe the solution you'd like**
Ideally it would be nice if the user could simply add an interface to their existing UDF class that provides one or more methods for implementing a RAPIDS execution path for the UDF.  The plugin would automatically detect the user's UDF implements the required RAPIDS execution interfaces and allow it to execute on the GPU rather than requiring a transition back to the CPU.

Ideally the implementation should provide:
- [x] user documentation on how to implement UDFs with an additional RAPIDS execution path, implemented by #1478 
- [x] a working example implementing a UDF leveraging cudf Java APIs (i.e.: does not require adding native code), implemented by #1393 and #1408
- [x] a working example implementing a UDF with a custom GPU kernel showing how to build and package the native code, implemented by #1472 

**Describe alternatives you've considered**
We could implement a completely separate interface, specific to the plugin, for registering UDFs.  This is less ideal since it's not as seamless.

**Comment by jlowe** [comment]
Features have been completed, closing this epic.
