### ISSUE TITLE
Releasing v0.3.0 - checklist

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#1397]
The checklist of releasing v0.3.0:
- [x] Update docs in spark-rapids
- [x] Update docs in spark-xgboost-examples
- [x] Pre-release
  - [x] Notification to team of last sprint of feature PRs
  - [x] Burndown
  - [x] Create branch-0.4
  - [x] Create auto-merge from 0.3 to 0.4
  - [x] Enable Jenkins builds for 0.4
    - [x] premerge build
    - [x] nightly build
    - [x] integration test
    - [x] performance test
  - [x] Set the default branch to branch-0.4
  - [x] cuDF 0.17 Java release to sonatype
  - [x] Notify RAPIDS team of javadocs for 0.17
  - [x] Merge any remaining branch-0.3 PRs
  - [x] Make a PR to sync from branch-0.3 to main
  - [x] Trigger the release Jenkins job on main branch and deploy the jar to sonatype staging
  - [x] Deliver packages to QA
- [x] QA signoff
  - [x] Sign off on QA test plan
  - [x] Performance benchmark
  - [x] Run integration tests against staging jars
  - [x] Run integration tests with AQE
  - [x] Run integration tests with UCX
  - [x] Run integration tests on Databricks AWS
  - [x] Run integration tests on Databricks Azure
  - [x] Run integration tests on Dataproc
  - [x] Run integration tests on AWS EMR
  - [x] Run LHA queries
  - [x] QA signoff on YARN or NGC
  - [x] QA signoff on A100
- [x] Virtual review
- [x] Release after QA signoff
  - [x] Update gh-pages branch
  - [x] Publish final changelog in 0.3 branch
  - [x] Create a PR(not squashed) to merge branch-0.3 to main branch with new version 0.3.0 and get it merged after passing premerge build
  - [x] Tag the release and deploy the staging artifacts to maven central repository
  - [x] Update `rapids.sh` in https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/rapids 
    - [x] https://github.com/GoogleCloudDataproc/initialization-actions/pull/847
