### ISSUE TITLE
[FEA]Add support for higher order function "aggregate" over window

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#1419]
**Is your feature request related to a problem? Please describe.**
Need to find a way to support higher order function "aggregate" on GPU

**Describe the solution you'd like**
SQL + Hive UDF.

Sub tasks:

- [x] cuDF Table needs to support explode on a column - cudf work https://github.com/rapidsai/cudf/pull/7140
- [x] cuDF Table needs to support explode on a column - JNI work https://github.com/rapidsai/cudf/pull/7151
- [x] Support collect_list (aka expression CollectList ) running on GPU with Windowing - cudf https://github.com/rapidsai/cudf/pull/7189
- [x] Support collect_list (aka expression CollectList ) running on GPU with Windowing - JNI test cases https://github.com/rapidsai/cudf/pull/7121
- [x] Support collect_list (aka expression CollectList ) running on GPU with Windowing - plugin https://github.com/NVIDIA/spark-rapids/pull/1548
- [x] Support struct (aka expression CreateNamedStruct) running on GPU - JNI + plugin
- [x] GPU Shuffle and GPU Sort support 'struct' type.  - plugin
- [x] HiveUDF supports array type
- [x] Check whether all the aggregates could be rewritten by cuDF APIs
- [x] Create CPU examples of using the Hive UDF to execute the aggregate, along with the SQL part.
- [x] Create GPU examples of using the Hive UDF to execute the aggregate, along with the SQL part.
- [x] Create a complete list of the aggregates
