### ISSUE TITLE
[FEA] Support features for user query

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#1608]
**Is your feature request related to a problem? Please describe.**

- [x] Support casting on nested types like lists, structs and maps. For example, we should be able to cast an Array(floats) to an Array(doubles) . We will need cudf change https://github.com/rapidsai/cudf/issues/7225 followed by https://github.com/NVIDIA/spark-rapids/issues/1604. We may need some JNI changes or could get away with existing changes on the java side depending on the cpp implementation.
- [x] Support Sort on keys that are nested types. cudf change  https://github.com/rapidsai/cudf/issues/7226 followed by https://github.com/NVIDIA/spark-rapids/issues/1605. We may need some JNI changes or could get away with existing changes on the java side depending on the cpp implementation.
- [x] Support Union with nested types https://github.com/NVIDIA/spark-rapids/issues/1459. I think we might be able to get away without cudf changes and handle it fully on the plugin side.
- [x] Support nested types to pass through for InMemoryTableScan and InMemoryRelation. https://github.com/NVIDIA/spark-rapids/issues/1582
- [x] Support nested types and input and output to RangePartitioning https://github.com/NVIDIA/spark-rapids/issues/1607

**Comment by wjxiz1992** [comment]
From the explain text, we still need an expression to support: 
```
!NOT_FOUND <DateFormatClass> date_format(cast(unix_timestamp(_c2#50, yyyy-MM-dd HH:mm:ss, Some(UTC)) as timestamp), yyyy-MM-dd HH:mm:ss, Some(UTC)) cannot run on GPU because no GPU enabled version of expression class org.apache.spark.sql.catalyst.expressions.DateFormatClass could be found
```

**Comment by sameerz** [comment]
We made some progress on this in 21.06 and will continue in 21.08.

**Comment by sameerz** [comment]
Completed work for union of nested types in 21.10
