### ISSUE TITLE
[TASK] Big Reliability Epic

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#1870]
We recently had an issue where `contiguousSplit` started to fail on 2GB partitions.  We know that there are some issues with  similar limits in shuffle #45 but it is the unknown unknowns that are more problematic because we cannot make informed decisions about prioritizing fixing these issues.

We need to come up with a test plan to really hammer on size limits in both cudf and this plugin so we can have a better understanding of what limits exist and so we can come up with a proper plan to address them.

**Avoid Crashes:**

Highest priority: 
 - [x] https://github.com/NVIDIA/spark-rapids/issues/5028
 - [x] https://github.com/NVIDIA/spark-rapids/issues/4968
 - [x] https://github.com/NVIDIA/spark-rapids/issues/5029
 - [x] https://github.com/NVIDIA/spark-rapids/issues/4061
 - [x] https://github.com/NVIDIA/spark-rapids/issues/5140
 - [x] https://github.com/NVIDIA/spark-rapids/issues/5108

Next on the list: 
 - [x] https://github.com/NVIDIA/spark-rapids/issues/3300
 - [x] https://github.com/NVIDIA/spark-rapids/issues/836
 - [x] https://github.com/NVIDIA/spark-rapids/issues/2354
 - [x] https://github.com/NVIDIA/spark-rapids/issues/302
 - [x] https://github.com/NVIDIA/spark-rapids/issues/3328

**Test for new issues:**
 - [x] Test common scenarios: avro #5657

**Auto Tune:**
 - [x] https://github.com/NVIDIA/spark-rapids/issues/2424

**Better Error Reporting:**
 - [x] https://github.com/rapidsai/cudf/issues/10553

**Comment by sameerz** [comment]
Discussed and need to break down larger work items into tasks.

**Comment by sameerz** [comment]
This is an epic that is being supported by other issues.  Not specific to a release.

**Comment by revans2** [comment]
This became a dumping ground for a lot of reliability issues. I am going to rename this. Remove everything that is not done, and then file new epics to track each of the individual issues.
