### ISSUE TITLE
[FEA] support collect aggregations

### ISSUE THREAD

**Issue by sperlingxx** [NVIDIA/spark-rapids#2062]
**Is your feature request related to a problem? Please describe.**
This is an umbrella issue for the support work of collect aggregations.

* window context
  - [x] collect_list
  - [x] collect_set
    - [x] cuDF native support [issue](https://github.com/rapidsai/cudf/issues/7809)   [PR](https://github.com/rapidsai/cudf/pull/7881)
    - [x] plugin support [PR](https://github.com/NVIDIA/spark-rapids/pull/2548) 
* groupBy context (high priority)
  - [x] cuDF native: 
    - [x] support null-excluded policy    [issue](https://github.com/rapidsai/cudf/issues/7777) [PR](https://github.com/rapidsai/cudf/pull/8044)
    - [x] grouped concatenate list/set    [issue](https://github.com/rapidsai/cudf/issues/7839) [PR](https://github.com/rapidsai/cudf/pull/8436)
   - [x] cuDF Java
     - [x] Java binding of `COLLECT_SET`  [PR](https://github.com/rapidsai/cudf/pull/8057)
     - [x] Java bindings of `MERGE_LISTS` and  `MERGE_SETS`  [PR](https://github.com/rapidsai/cudf/pull/8516)
  - [x] plugin support [issue](https://github.com/NVIDIA/spark-rapids/issues/2916)
* reduction context  
  - [x] [(issue) cuDF native support](https://github.com/rapidsai/cudf/issues/7807)
    - [x] cuDF native
      - [x] [Add scalar support for lists](https://github.com/rapidsai/cudf/issues/5887)
      - [x] [Default constructors for list_scalars](https://github.com/rapidsai/cudf/issues/9032) 
    - [x]  cuDF Java support
  - [x] cuDF native support: reduction concatenate_list
    - [x] cuDF Java support
  - [x] cuDF native support: reduction concatenate_set
    - [x] cuDF Java support 
  - [x]  plugin support

**Comment by mythrocks** [comment]
Hello, @sperlingxx. I didn't realize at the time that you'd picked up https://github.com/rapidsai/cudf/issues/7809. It would be best to postpone this until the rolling-window dispatch logic is reworked.

The tests you've written are good: comprehensive and reusable. The implementation will likely have changes, after the dispatch redesign. My apologies for not having caught this before you began work on this.

**Comment by sperlingxx** [comment]
The plugin support of groupBy context is 75% done, because 3 out of 4 sub-tasks are done. The remaining unfinished(WIP) task is nice to have, since we introduced a feature in task 3 which falls back all stages of Aggregate to CPU associately in case of unexpected crashes.

**Comment by sperlingxx** [comment]
Close this issue since all sub tasks under these issue are cleaned.
