### ISSUE TITLE
[WIP] [BUG] Fix CSV Parsing

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#2063]
Still working on filling this out. Will update it as I add more things today.

**Describe the bug**
I am not totally sure if this is a bug or an epic, but I have marked it as both. CSV parsing has been on by default, but it has a lot of inconsistencies with what spark does and this can cause problems.  The current plan is to mitigate this by disabling CSV by default and then working through issues until we can enable it again everywhere.

Bugs Issues:

- [ ] `multiline` support TODO file issue Spark has multiline support off by default, cudf only supports multiline. We have been ignoring this (High Priority).

Low Priority Issues:
- [ ] Header with lots of comments at the beginning. We currently play games with turning off header checking in all but the first partition for a file. This is fine, so long as the first partition is more than just comments.  This is minor, and possibly a bug in Spark as well.
- [ ] Support alternate character sets ("encoding" option).
- [ ] Support `FAILFAST` mode. By default when Spark sees malformed data it converts it into a null `PERMISSIVE` mode. In `FAILFAST` mode it throws an exception.  There is also `DROPMALFORMED` mode that is supposed to drop bad data, but it looks like CSV does not support this.

Tests:
- [ ] Add tests for `enforceSchema` set to false. TODO file issues Oddly for Spark when you set this to false it does more schema enforcement.  The enforce here really means force the set schema on the files. It looks like it works for our plugin, but we want to have tests to verify this
