### ISSUE TITLE
[FEA] Record GPU time and Fetch time separately, instead of recording Total Time

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2334]
**Is your feature request related to a problem? Please describe.**
The `totalTime` metric can be confusing because it often (but not always) includes the execution time of the child operator(s). It would be better to separately record `fetchTime` and `gpuOpTime`, although this may be difficult or not possible in some cases.

Making this change will also provide better metrics that we can use when profiling queries or developing a better cost model for CBO.

**Describe the solution you'd like**

Review the following operators and determine whether we can improve the metrics to record the GPU time and fetch time separately. File new issues for those that we plan on doing this for.

- [x] GpuBroadcastExchangeExec - No action required
- [x] GpuBroadcastHashJoinExec - No action required
- [x] GpuBroadcastNestedLoopJoinExec - No action required
- [x] GpuBroadcastToCpuExec - No action required
- [x] GpuCartesianProductExec - No action required
- [x] GpuCoalesceBatchesExec - No action required
- [x] GpuHashAggregateExec - No action required
- [x] GpuRowToColumnarExec https://github.com/NVIDIA/spark-rapids/issues/2820
- [x] GpuShuffleCoalesceExec - No action required
- [x] GpuShuffledHashJoinExec - No action required
- [x] GpuSortExec - No action required
- [x] GpuTopN - No action required
- [x] HostColumnarToGpuExec - No action required
- [x] GpuUnionExec #2586
- [x] GpuExpandExec #2512
- [x] GpuGenerateExec #2512
- [x] GpuRangeExec #2512
- [x] GpuColumnarToRowExec #2269
- [x] GpuFilterExec #2461 
- [x] GpuGlobalLimitExec #2461
- [x] GpuLocalLimitExec #2461
- [x] GpuProjectExec #2461
- [x] GpuWindowExec #2461

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by andygrove** [comment]
@nartal1 fyi - this may have an impact on the profiling tools
