### ISSUE TITLE
[FEA] Rework the shim layer to robustly handle ABI and API incompatibilities across Spark releases

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#3223]
**Is your feature request related to a problem? Please describe.**

Apache Spark uses [semantic versioning major.feature.patch](https://spark.apache.org/versioning-policy.html), e.g. 3.1.2. 
- Most compatibility promises are moot for the Plugin because our integration points are in the developer API and internal API land, not the Public APIs this language pertains to. 
- Even if the compatibility guarantees were applicable we need to deal with breaking changes because we support multiple feature release lines 3.0.1+, 3.1.1+, and the future 3.2.x. In practice, incompatibilities at the API and ABI level may occur much more often in internal APIs.
- Per documentation and simple bytecode comparison, even if there is compatibility, there is often no ABI compatibility, just API (source) compatibility requiring recompilation. Thus our current implementation relying on the version-independent compilation using 3.0.1 as a dependency runs into runtime failures with the other Spark versions that is only detected with tests.

**Describe the solution you'd like**
A solution that catches 99% of the issues at build time and is robust at run time.

**Describe alternatives you've considered**
Rely on the existing solution that is based on test coverage to identify the issues at run time

**Additional context**
Prototype branches such as 
- https://github.com/gerashegalov/spark-rapids/tree/reshim-source-deps-classifier-and-parallel-classloader-spark320-2
- https://github.com/gerashegalov/spark-rapids/tree/reshim-source-deps-classifier-and-parallel-classloader-spark320-refactor-on-the-fly

Tasks:
- [x] Build one spark version at a time  - https://github.com/NVIDIA/spark-rapids/issues/3224
- [x]  Add shimming against incompatibility "inherited" via changes to catalyst TreeNode derivatives  - https://github.com/NVIDIA/spark-rapids/pull/3323
- [x] Classloader changes - https://github.com/NVIDIA/spark-rapids/pull/3381
- [x] Build changes for combining classifier versions of Spark into single dist package - https://github.com/NVIDIA/spark-rapids/issues/3223#issue-969324171
- [x] https://github.com/NVIDIA/spark-rapids/issues/3338
- [x] #3495
- [x] ParquetCachedBatchSerializer move to common place for all spark 3.1+ builds - https://github.com/NVIDIA/spark-rapids/issues/3314
- [x] Fix any deploy targets and update jenkins builds
- [x] deduplicate shim layer code 
  - [x] source code level dedupe of internal classes with the sole difference in the package name - https://github.com/NVIDIA/spark-rapids/pull/3577
  - [x] binary class file level dedupe that consolidates identical classes even though compiled under different Spark versions  in spark3xx-common https://github.com/NVIDIA/spark-rapids/pull/3545
- [x] remove unneeded build profiles after switching 
- [x] reduce pom sizes by refactoring https://github.com/NVIDIA/spark-rapids/pull/3411#discussion_r705908151
- [x] remove 301emr shim - https://github.com/NVIDIA/spark-rapids/pull/3443
- [x] Test udf-examples native build
- [x]  test UCX with all shim flavors
- [x] Kryo registartion: https://github.com/NVIDIA/spark-rapids/issues/3468
- [x] All 3.2 integration tests pass https://github.com/NVIDIA/spark-rapids/issues/3483

These are optional or nice to have tasks:
- [x] Integration tests should only pick up one jar, also would need update builds for individual spark jars
- [x] Build scripts to build all easily
- [ ] external facing api's into its own module (optional)

**Comment by abellina** [comment]
Should we add a subtask about testing with UCX for each Spark distro?

**Comment by gerashegalov** [comment]
@abellina sure, go ahead re:  testing with UCX for each Spark distro. Also we have the optimization / fix you suggested offline about triggering the shuffle manager init on the driver earlier that you can add

**Comment by tgravescs** [comment]
udf build is passing so marking that off

**Comment by tgravescs** [comment]
all required tasks are complete so closing this.
