### ISSUE TITLE
Qualification tool improvements

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3792]
**Is your feature request related to a problem? Please describe.**
We want to improve the qualification output to give user higher level of confidence a query is a good candidate for GPU.  In this case we only want to rely on the eventlog initially as anything else like explain API is something else the user has to run.  I don't really know how to improve it more without parsing the specific SQL operators and either see if we think they would run on the GPU and/or use some heuristics about the metrics and operator types.

We can try to provide more stats like:
- was there a particular stage in the SQL query that was the largest.  If so can we determine the sql operators in that stage (we can only sometimes do this from event log). Of those operators which one took longest.  Is that operator something we might do on the GPU.  Challenge here is we do not know the types of the input to all the operators. We have some of the schema from file input.  If do this definitely need asterisk by data types saying make sure we support it.
- Put together input/output sizes and shuffle sizes to see if its too small data
- skew data checks
- Look at particular operators we know generally do well - window operator, transcoding.  I don't think there is a way for us to decide if its High cardinality processing​ (joins, sorts, aggregations)

We want to put as much information we can into the ranking of the applications and then also be able to display what information we used to the user so they can understand why we chose that ranking.

We could also analyze the NDS queries in detail and how the qualification tool scores them to see if we can find other heuristics to add to make the qualification tool score better.  Including things we could reports for potential problems, etc.

Can we determine env to see if possible I/O bottle necks?  Like could we have them fill in information about network/disks, etc... not sure on this one.

Also investigate adjust the scores based on failed tasks/stages/etc..

Can we be more fine grain for RDD/Dataset that still have some dataframe operations. Right now we exclude the entire SQL ops when we see that, perhaps we can determine which parts better.

Other issues that go along with this.

- [x] https://github.com/NVIDIA/spark-rapids/issues/5176
- [x] https://github.com/NVIDIA/spark-rapids/issues/5263
- [x] https://github.com/NVIDIA/spark-rapids/issues/5269
- [x] https://github.com/NVIDIA/spark-rapids/issues/5358
- [x] https://github.com/NVIDIA/spark-rapids/issues/5361
- [x] https://github.com/NVIDIA/spark-rapids/issues/5362
- [x] https://github.com/NVIDIA/spark-rapids/issues/5363
- [x] https://github.com/NVIDIA/spark-rapids/issues/5364
- [x] https://github.com/NVIDIA/spark-rapids/issues/5512
- [x] https://github.com/NVIDIA/spark-rapids/issues/5563
- [x] https://github.com/NVIDIA/spark-rapids/issues/5564
- [x] https://github.com/NVIDIA/spark-rapids/issues/5565
- [x] https://github.com/NVIDIA/spark-rapids/issues/5566
- [x] https://github.com/NVIDIA/spark-rapids/issues/5567
- [x] https://github.com/NVIDIA/spark-rapids/issues/5569
- [x] https://github.com/NVIDIA/spark-rapids/issues/5570
- [x] https://github.com/NVIDIA/spark-rapids/issues/5543
- [x] https://github.com/NVIDIA/spark-rapids/issues/5517
