### ISSUE TITLE
[FEA] Support decimal type

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#42]
**Is your feature request related to a problem? Please describe.**
Decimal Support (in order of priority):

- [x] FIXED_LEN_BYTE_ARRAY read parquet https://github.com/NVIDIA/spark-rapids/issues/1324
- [x] Basic Read Parquet https://github.com/NVIDIA/spark-rapids/pull/1294
- [x] Join https://github.com/NVIDIA/spark-rapids/issues/1325
- [x] Simple Hash Aggregates https://github.com/NVIDIA/spark-rapids/issues/1316
- [x] Broadcast https://github.com/NVIDIA/spark-rapids/issues/1326
- [x] Sort and Shuffle https://github.com/NVIDIA/spark-rapids/issues/1328
- [x] Cast https://github.com/NVIDIA/spark-rapids/issues/1330
- [x] Add, Subtract, multiply, IntegerDivide and null safe equals https://github.com/NVIDIA/spark-rapids/issues/1329
- [x] Union and ExpandExec https://github.com/NVIDIA/spark-rapids/issues/1331
- [x] CaseWhen, Coalesce and IfElse https://github.com/NVIDIA/spark-rapids/issues/1332
- [x] Window Operations https://github.com/NVIDIA/spark-rapids/issues/1333
- [x] Aggregate Count https://github.com/NVIDIA/spark-rapids/issues/1334 
- [x] Round/Bround issue #37, PR https://github.com/NVIDIA/spark-rapids/pull/1244

Lower priority not seen in TPC-DS
- [X] Pmod, divide, and remainder #1572
- [x] CollectLimitExec https://github.com/NVIDIA/spark-rapids/issues/1335
- [x] Read ORC Support
- [x] Read CSV and JSON Support https://github.com/NVIDIA/spark-rapids/issues/4824
- [x] Write Parquet Support #1485 
- [x] Write ORC Support
- [X] Decimal Casts to String and String to Decimal #1625
- [x] GenerateExec PR #1410
- [X] Python Arrow Processing https://github.com/rapidsai/cudf/issues/7116
- [X] Unary Ops (abs, ceil, floor, UnaryMinus, UnaryPositive) #1425
- [X] AtLeastNNonNulls PR #1410
- [X] GetArrayItem/GetStructField PR #1410
- [X] Greatest/Least
- [X] In/InSet PR #1410

This issue builds on https://github.com/rapidsai/cudf/issues/6515

**Comment by sameerz** [comment]
This is an umbrella issue for decimal support. We will tag other decimal related issues to this one.

**Comment by sperlingxx** [comment]
I think #37 is related to this issue.

**Comment by razajafri** [comment]
> I think #37 is related to this issue.

Yes, it's related and listed in the table above

**Comment by sameerz** [comment]
Decimal writing is still unsupported for JSON, Avro and CSV.  That work will be tracked in epics for those writers.
