### ISSUE TITLE
[FEA] Plugable Cache

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#444]
This issue deals with creating a plug-able cache and will be changed as we find more stuff that needs to be worked on. 

- [x] [Create a Plug-able cache serializer assuming we have the plugin enabled and the data is all going back on the host.](https://github.com/NVIDIA/spark-rapids/pull/638) 
- [x] [InMemoryTableScanExec needs to be implemented which needs to be smart enough to make sure we don't copy the data back to host unless its needed.](https://github.com/NVIDIA/spark-rapids/pull/638)  
- [x] Performance analysis. This will mostly be testing how fast are we reading the cache back compared to the CPU. 
- [x] Come up with a real world example. This was done as a part of the performance analysis, nothing was checked-in yet. 
- [x] [We see a lot of row/col conversions, get rid of the unnecessary ones.](https://github.com/NVIDIA/spark-rapids/pull/638) 
- [x] [Reading CachedBatch to InternalRow](https://github.com/NVIDIA/spark-rapids/pull/843) 
- [x] [Write InternalRow to CachedBatch](https://github.com/NVIDIA/spark-rapids/pull/910)
- [x] [Write ColumnarBatch to CachedBatch on CPU](https://github.com/NVIDIA/spark-rapids/pull/1001)
- [x] [Read ColumnarBatch from CachedBatch on CPU](https://github.com/NVIDIA/spark-rapids/pull/1001)
- [x] Handle CalendarIntervalType and NullType in Cached Batch. [Issue](https://github.com/NVIDIA/spark-rapids/issues/913)/[PR](https://github.com/NVIDIA/spark-rapids/pull/1080)
- [x] Handle nested types with CalendarIntervalType and NullType. [Issue](https://github.com/NVIDIA/spark-rapids/issues/1092)/[PR](https://github.com/NVIDIA/spark-rapids/pull/1183)
- [x] Improve the Parquet Serializer to handle large batches that may exceed Int.MAX_SIZE [Issue](https://github.com/NVIDIA/spark-rapids/issues/685)/[PR](https://github.com/NVIDIA/spark-rapids/pull/1265)

**Comment by sameerz** [comment]
Coding work in 0.2, but will target Spark 3.1 release.  Depends on https://github.com/apache/spark/pull/29067
