### ISSUE TITLE
[FEA] Add ANSI support 

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#5120]
**Is your feature request related to a problem? Please describe.**
We have ANSI support for some of the SQL functions/operators and casting but it is not completely in sync with everything that Spark supports. This epic is to list out the gaps and track the remaining issues.

## P1 issues 
- [ ] https://github.com/NVIDIA/spark-rapids/issues/4151
- [ ] https://github.com/NVIDIA/spark-rapids/issues/4811
- [ ] https://github.com/NVIDIA/spark-rapids/issues/5119
- [ ] https://github.com/NVIDIA/spark-rapids/issues/2936
- [ ] https://github.com/NVIDIA/spark-rapids/issues/3575
- [ ] https://github.com/NVIDIA/spark-rapids/issues/5113

## P2 issues
- [ ] https://github.com/NVIDIA/spark-rapids/issues/5114
- [ ] https://github.com/NVIDIA/spark-rapids/issues/5115
- [ ] https://github.com/NVIDIA/spark-rapids/issues/5116
- [ ] https://github.com/NVIDIA/spark-rapids/issues/5117
