### ISSUE TITLE
[FEA] Plugin should throw same arithmetic exceptions as Spark

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#5196]
**Is your feature request related to a problem? Please describe.**
This is a follow-on to https://github.com/NVIDIA/spark-rapids/issues/5182 where we made some exception checks less specific due to changes in Spark 3.3 causing test failures.

We really should throw the same arithmetic exceptions as Spark and these vary by Spark version.

**Describe the solution you'd like**
Update `arithmetic_ops_test.py` and `logic_test.py` to check for specific exceptions `java.lang.ArithmeticException` vs `org.apache.spark.SparkArithmeticException`.

**Describe alternatives you've considered**
None

**Additional context**
This is a checklist of all the tests we need to update.
- [x] `test_mod_pmod_by_zero` (#5354)
- [x] `test_unary_minus_ansi_overflow` (#5783)
- [x] `test_abs_ansi_overflow` (#5783)
- [x] `test_floor_ceil_overflow` (#5915)
- [x] `test_div_by_zero_ansi` (#5354)
- [x] `test_div_overflow_exception_when_ansi` (#5354)
- [x] `test_unary_minus_ansi_overflow_day_time_interval`(#5783)
- [x] `test_abs_ansi_overflow_day_time_interval`(#5783)
- [x] `test_add_overflow_with_ansi_enabled_day_time_interval`(#5949)
- [x] `test_subtraction_overflow_with_ansi_enabled_day_time_interval`(#5949)
- [x] `test_day_time_interval_division_overflow`(#6019)
- [x] `test_logical_with_side_effect`(#5949)
- [x] `test_add_overflow_with_ansi_enabled` (#6071)
- [x] `test_subtraction_overflow_with_ansi_enabled`(#6071)

**Comment by HaoYang670** [comment]
Our plugin currently throw `java.lang.ArithmeticException`. Should we update it to throw `SparkArithmeticException`?
```scala
  def divByZeroError(): Nothing = {
    throw new ArithmeticException("divide by zero")
  }

  def divOverflowError(): Nothing = {
    throw new ArithmeticException("Overflow in integral divide.")
  }
```
https://github.com/NVIDIA/spark-rapids/blob/branch-22.06/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala#L704-L710


Maybe we should put these functions into the shim layers.

**Comment by jlowe** [comment]
> Should we update it to throw SparkArithmeticException?

Yes.  As noted in the issue description:
```
We really should throw the same arithmetic exceptions as Spark and these vary by Spark version.
```

There's already a `RapidsErrorUtils` class that is shimmed by Spark version to throw the proper exception type for various errors.  I would expect these exceptions to be added to that class or maybe a similar shim'd class added to handle arithmetic exceptions.

**Comment by HaoYang670** [comment]
Could we directly use `overflowInIntegralDivideError` and `divideByZeroError` in Spark instead of implementing our own?

**Comment by jlowe** [comment]
> Could we use QueryExecutionErrors in Spark instead of implementing our own?

We already do, see `RapidsErrorUtils`.  We cannot use `QueryExecutionErrors` directly in common code because it wasn't added until Spark 3.2.0.  That's why we use a shim'd class like `RapidsErrorUtils` to handle throwing the appropriate error, whether that's a standard Java exception or leveraging Spark's `QueryExecutionErrors` to throw a Spark-specific exception.

**Comment by HaoYang670** [comment]
For `test_day_time_interval_division_overflow`, it is a little dificult to update the type of exceptions, because there are some exceptions which don't have the correspondence in Spark: https://github.com/NVIDIA/spark-rapids/blob/branch-22.08/sql-plugin/src/main/330%2B/scala/org/apache/spark/sql/rapids/shims/intervalExpressions.scala#L97-L120
(We need to create a new `errorClass` in `SparkArithmeticException`, such as `UNSUPPORTED_VALUE`)

**Comment by revans2** [comment]
> `test_day_time_interval_division_overflow`

Could you please get the exceptions that Spark is throwing that we want to match, including the stack trace?

From reading the code it looks like the error checking for Spark in the case of NaN and Inf is happening inside `roundToInt`

https://github.com/apache/spark/blob/3fde0ba6e67ca45e25e8a19e9bc8f8371f12cb71/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/intervalExpressions.scala#L519

It appears that it will throw a regular `ArithmeticException` not a `SparkArithmeticException`. So it would be nice to understand exactly what spark is doing.

**Comment by HaoYang670** [comment]
> Could you please get the exceptions that Spark is throwing that we want to match, including the stack trace?
Test on branch 22.08, using Spark 330

Stack trace of Spark:
```
```
Stack trace of spark-rapids:
```
java.lang.ArithmeticException: Has NaN
        at org.apache.spark.sql.rapids.shims.IntervalUtils$.$anonfun$checkDoubleInfNan$5(intervalExpressions.scala:119)
        at org.apache.spark.sql.rapids.shims.IntervalUtils$.$anonfun$checkDoubleInfNan$5$adapted(intervalExpressions.scala:117)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at org.apache.spark.sql.rapids.shims.IntervalUtils$.withResource(intervalExpressions.scala:27)
        at org.apache.spark.sql.rapids.shims.IntervalUtils$.checkDoubleInfNan(intervalExpressions.scala:117)
        at org.apache.spark.sql.rapids.shims.IntervalUtils$.roundDoubleToLongWithOverflowCheck(intervalExpressions.scala:148)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.$anonfun$doColumnar$8(intervalExpressions.scala:555)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.withResource(intervalExpressions.scala:512)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.doColumnar(intervalExpressions.scala:553)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.doColumnar(intervalExpressions.scala:526)
        at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$3(GpuExpressions.scala:256)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.withResourceIfAllowed(intervalExpressions.scala:512)
        at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$2(GpuExpressions.scala:253)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.withResourceIfAllowed(intervalExpressions.scala:512)
        at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:252)
        at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:251)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.columnarEval(intervalExpressions.scala:512)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
        at com.nvidia.spark.rapids.GpuAlias.columnarEval(namedExpressions.scala:109)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
        at com.nvidia.spark.rapids.GpuExpressionsUtils$.columnarEvalToColumn(GpuExpressions.scala:93)
        at com.nvidia.spark.rapids.GpuProjectExec$.projectSingle(basicPhysicalOperators.scala:102)
        at com.nvidia.spark.rapids.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:109)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:216)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:213)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:213)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:248)
        at com.nvidia.spark.rapids.GpuProjectExec$.project(basicPhysicalOperators.scala:109)
        at com.nvidia.spark.rapids.GpuProjectExec$.projectAndClose(basicPhysicalOperators.scala:73)
        at com.nvidia.spark.rapids.GpuProjectExec.$anonfun$doExecuteColumnar$1(basicPhysicalOperators.scala:149)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:241)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:187)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:238)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:215)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:255)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:364)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:136)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by HaoYang670** [comment]
For these 2 test cases:
```
    (FloatType(), [timedelta(seconds=1), float('NaN')]),
    (DoubleType(), [timedelta(seconds=1), float('NaN')]),
```
Both Spark and rapids throws `has nan` exception.
Stack trace of Spark
```
22/07/13 09:08:22 WARN TaskSetManager: Lost task 3.0 in stage 2.0 (TID 11) (remzi-desktop executor driver): java.lang.ArithmeticException: input is infinite or NaN
        at org.sparkproject.guava.math.DoubleMath.roundIntermediate(DoubleMath.java:54)
        at org.sparkproject.guava.math.DoubleMath.roundToLong(DoubleMath.java:149)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:364)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:136)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
Stack trace of rapids:
```
22/07/13 09:08:22 ERROR Executor: Exception in task 3.0 in stage 3.0 (TID 15)
java.lang.ArithmeticException: Has NaN
        at org.apache.spark.sql.rapids.shims.IntervalUtils$.$anonfun$checkDoubleInfNan$5(intervalExpressions.scala:119)
        at org.apache.spark.sql.rapids.shims.IntervalUtils$.$anonfun$checkDoubleInfNan$5$adapted(intervalExpressions.scala:117)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at org.apache.spark.sql.rapids.shims.IntervalUtils$.withResource(intervalExpressions.scala:27)
        at org.apache.spark.sql.rapids.shims.IntervalUtils$.checkDoubleInfNan(intervalExpressions.scala:117)
        at org.apache.spark.sql.rapids.shims.IntervalUtils$.roundDoubleToLongWithOverflowCheck(intervalExpressions.scala:148)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.$anonfun$doColumnar$8(intervalExpressions.scala:555)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.withResource(intervalExpressions.scala:512)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.doColumnar(intervalExpressions.scala:553)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.doColumnar(intervalExpressions.scala:526)
        at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$3(GpuExpressions.scala:256)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.withResourceIfAllowed(intervalExpressions.scala:512)
        at com.nvidia.spark.rapids.GpuBinaryExpression.$anonfun$columnarEval$2(GpuExpressions.scala:253)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed(Arm.scala:73)
        at com.nvidia.spark.rapids.Arm.withResourceIfAllowed$(Arm.scala:71)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.withResourceIfAllowed(intervalExpressions.scala:512)
        at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval(GpuExpressions.scala:252)
        at com.nvidia.spark.rapids.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:251)
        at org.apache.spark.sql.rapids.shims.GpuDivideDTInterval.columnarEval(intervalExpressions.scala:512)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
        at com.nvidia.spark.rapids.GpuAlias.columnarEval(namedExpressions.scala:109)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
        at com.nvidia.spark.rapids.GpuExpressionsUtils$.columnarEvalToColumn(GpuExpressions.scala:93)
        at com.nvidia.spark.rapids.GpuProjectExec$.projectSingle(basicPhysicalOperators.scala:102)
        at com.nvidia.spark.rapids.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:109)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:216)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:213)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:213)
        at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:248)
        at com.nvidia.spark.rapids.GpuProjectExec$.project(basicPhysicalOperators.scala:109)
        at com.nvidia.spark.rapids.GpuProjectExec$.projectAndClose(basicPhysicalOperators.scala:73)
        at com.nvidia.spark.rapids.GpuProjectExec.$anonfun$doExecuteColumnar$1(basicPhysicalOperators.scala:149)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:241)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.withResource(GpuColumnarToRowExec.scala:187)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:238)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:215)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:255)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:364)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:136)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by HaoYang670** [comment]
Close this PR as all subtasks has been done. Feel free to reopen it if anyone some other opinions.
