### ISSUE TITLE
[FEA] Improve casting performance.

### ISSUE THREAD

**Issue by nvdbaranec** [NVIDIA/spark-rapids#5639]
The casting code in the plugin is currently a collection of expensive string manipulation functionality (regex, etc).  It exists to handle more exotic edge cases coming from CSV and JSON that don't work correctly in cudf itself.  Ideally, these conversions could be done as a set of custom kernels directly in the spark-rapids-jni.   

Tasks

- [x] [Kernels for float/double](https://github.com/NVIDIA/spark-rapids-jni/issues/632)
- [x] [Kernel for integers](https://github.com/NVIDIA/spark-rapids-jni/issues/444)
- [x] [Kernel for decimals](https://github.com/NVIDIA/spark-rapids/issues/6401)
- [ ] Kernel for timestamps
- [ ] Kernel for durations
- [ ] Kernel for bools

Related items:
https://github.com/NVIDIA/spark-rapids/issues/4969
https://github.com/NVIDIA/spark-rapids/issues/4837

**Comment by nvdbaranec** [comment]
Closing for now unless perf testing highlights it again.
