### ISSUE TITLE
[FEA] Add Spark 3.4.0 to regular premerge/nightly build in 23.06

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5824]
**Is your feature request related to a problem? Please describe.**
For 22.08 we are removing the Spark 3.4.0 build from the regular premerge and nightly and going to build it separately. For 22.12 we want to add that back.

https://github.com/NVIDIA/spark-rapids/pull/6999

```[tasklist]
### Tasks
- [x] Enable Spark 3.4 build in pre-merge making it optional(i.e this build should not block merging a PR) - https://github.com/NVIDIA/spark-rapids/pull/6999
- [x] Enable Spark-3.4 build & unit test in pre-merge - https://github.com/NVIDIA/spark-rapids/pull/8218
- [x] Enable Spark-3.4 in regular nightlies instead of a separate pipeline
```

**Comment by NVnavkumar** [comment]
Confirmed the integration tests are now running in regular nightly pipeline. Closing this issue now.
