### ISSUE TITLE
[DOC] Update Qualification Tool documentation to reflect new default speedup factors + expression support + app view

### ISSUE THREAD

**Issue by mattahrens** [NVIDIA/spark-rapids#5843]
**Report needed documentation**
As we are making changes to the qualification tool in 22.08, we need to make sure documentation is updated.

**Describe the documentation you'd like**
Update details related to new default speedup factors + expression support + app view details.

Subtasks:

- [X] add app-details to qualification tools doc - https://github.com/NVIDIA/spark-rapids/issues/5963
- [x] add support parsing expressions to qualification tool - https://github.com/NVIDIA/spark-rapids/issues/5964
- [x] Add estimated speedup factors to qualification tools - https://github.com/NVIDIA/spark-rapids/issues/5965

**Comment by amahussein** [comment]
The subtasks were done in 22.08.
