### ISSUE TITLE
[TASK] Run without fatal OOMs

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#6746]
This epic is trying to group together tasks that will help us achieve a pretty tall order, which is to run without fatal OOMs. Non-fatal OOMs are defined as those we can handle via spill or, in the last resort, via retries.

Tasks will be added to this epic as we define this work better.

Better use of GPU memory:
- [x] https://github.com/NVIDIA/spark-rapids/issues/6758
- [x] https://github.com/NVIDIA/spark-rapids/issues/6561
- [x] https://github.com/NVIDIA/spark-rapids/issues/6768
- [x] https://github.com/NVIDIA/spark-rapids/issues/6784
- [x] https://github.com/NVIDIA/spark-rapids/issues/6785

Better OOM reporting:

- [x] https://github.com/NVIDIA/spark-rapids/issues/6744
- [x] https://github.com/rapidsai/cudf/issues/11970

Handle known OOMs:
- [x] https://github.com/NVIDIA/spark-rapids/issues/3300
- [x] https://github.com/NVIDIA/spark-rapids/issues/2354
- [x] https://github.com/NVIDIA/spark-rapids/issues/6983

**Comment by abellina** [comment]
Mentioning this issue: https://github.com/NVIDIA/spark-rapids/issues/6817, I am not sure it is part of this epic right now.

**Comment by revans2** [comment]
This epic is rather generic. I am removing all of the unfinished issues and will file new epics as needed to put them in.
