### ISSUE TITLE
[TASK] Multi-threaded shuffle improvements

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#6787]
This epic tracks improvements to the multi-threaded shuffle mode (in RapidsShuffleManager) that we'd like to pursue in the short term:

- [ ] Automatically tune shuffle write and read threads
- [ ] Implement a multi threaded version of the External Sorted Shuffle Writer
- [ ] Implement analysis code in the profiling tool to summary shuffle metrics
- [ ] Improve thread usage for writers and readers not assigning threads to tasks statically

- [ ] Investigate other compression codecs and other serializers.
- [ ] Investigate how to speed up the combine phase where a single file is written per map_id
