### ISSUE TITLE
[FEA] Support time zones that are not UTC

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#6839]
**Is your feature request related to a problem? Please describe.**
This is related to #6603 but a super set of it. I will list out the issues here to complete both sets of work, and then reference some of them in #6603 too.

The following are the tasks to do

* [ ] https://github.com/NVIDIA/spark-rapids/issues/6831
* [ ] https://github.com/NVIDIA/spark-rapids/issues/6832
* [ ] https://github.com/NVIDIA/spark-rapids/issues/6834
* [ ] https://github.com/NVIDIA/spark-rapids/issues/6835
* [ ] https://github.com/NVIDIA/spark-rapids/issues/6836
* [ ] https://github.com/NVIDIA/spark-rapids/issues/6838

In general we are going to try to have timestamps follow what Spark does and store them in UTC. Then convert the inputs to the desired timezone whenever we need to operate on it in a different time zone. 

(THIS IS STILL WIP. I HAVE A LOT MORE ISSUES TO FILE STILL)

**Comment by nvliyuan** [comment]
Not sure if `FromUTCTimestamp support PST` should be a sub task.

**Comment by res-life** [comment]
Follow on issue: https://github.com/NVIDIA/spark-rapids/issues/9570

**Comment by revans2** [comment]
Adding in some issues for testing too 

https://github.com/NVIDIA/spark-rapids/issues/9627

https://github.com/NVIDIA/spark-rapids/issues/9633

**Comment by res-life** [comment]
Test cases statistics:
|code snapshot|TZ|passed|skipped|xfailed|xpassed|
|:-|:-|:-|:-|:-|:-|
|Before #9773|UTC|TODO|TODO|TODO|TODO|
|After #9773|non-UTC|7589|2214|3719|8613|

**Comment by res-life** [comment]
Not planing work on this for release 24.04
@sameerz can we move it to next release?
