### ISSUE TITLE
[BUG] Unit Test failures in Spark-3.4 SNAPSHOT build

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#6987]
Umbrella bug to track all unit test failures in Spark-3.4 build.

**Steps/Code to reproduce bug**
```
$ mvn clean package -Dbuildver=340   
```

**Expected behavior**
no unit test failures

**Environment details (please complete the following information)**
local

Tasks:
## OrcEncryptionSuite
- [x] https://github.com/NVIDIA/spark-rapids/issues/7751

## CastOpSuite 
- [x] https://github.com/NVIDIA/spark-rapids/issues/7752

## ParquetFormatScanSuite
- [x] https://github.com/NVIDIA/spark-rapids/issues/7754

## WindowFunctionSuite  & CostBasedOptimizerSuite 
- [x]  https://github.com/NVIDIA/spark-rapids/issues/7755

## AdaptiveQueryExecSuite 
- [x] https://github.com/NVIDIA/spark-rapids/issues/7756

## AnsiCastOpSuite
- [x] https://github.com/NVIDIA/spark-rapids/issues/7757

## ParquetWriterSuite
- [x] #7018 

## HashAggregatesSuite
- [x]  https://github.com/NVIDIA/spark-rapids/issues/7014

## AdaptiveQueryExecSuite
- [x] #7054 

## ParquetFormatScanSuite
- [x] #7039

## AnsiCastOpSuite:
- [x] Write bytes to string
- [x] Write shorts to string
- [x] Write ints to string
- [x] Write longs to string 
- [x] Write ints to long
- [x] Write longs to int (values within range) 
- [x] Write longs to short (values within range) 
- [x] Write longs to byte (values within range) 
- [x] Write ints to short (values within range) 
- [x] Write ints to byte (values within range) 
- [x] Write shorts to byte (values within range)
- [x] Write floats to long (values within range) 
- [x] Write floats to int (values within range) 
- [x] Write floats to short (values within range)
- [x] Write floats to byte (values within range)
- [x] Write doubles to long (values within range)
- [x] Write doubles to int (values within range)
- [x] Write doubles to short (values within range)
- [x] Write doubles to byte (values within range)

```[tasklist]
### Tasks
- [x] https://github.com/NVIDIA/spark-rapids/pull/7025
```

**Comment by GaryShen2008** [comment]
Move out of 22.12 since it's for Spark 3.4.

**Comment by NVnavkumar** [comment]
All the underlying issues in this task list have been resolved, so closing this issue.

**Comment by NVnavkumar** [comment]
Verified that all unit tests are currently passing on Spark 3.4 build. Closing this now.
