### ISSUE TITLE
[BUG] Integration test failures in Spark - 3.4 SNAPSHOT build

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#6991]
**Describe the bug**
This is umbrella issue to track all integration test failure issues in Spark-3.4 build.

```[tasklist]
### Tasks
- [x] https://github.com/NVIDIA/spark-rapids/issues/6988
- [x] https://github.com/NVIDIA/spark-rapids/issues/6989
- [x] https://github.com/NVIDIA/spark-rapids/issues/6990
- [ ] https://github.com/NVIDIA/spark-rapids/issues/7216
- [ ] https://github.com/NVIDIA/spark-rapids/issues/8012
- [ ] https://github.com/NVIDIA/spark-rapids/issues/8015
- [ ] https://github.com/NVIDIA/spark-rapids/issues/8016
- [ ] https://github.com/NVIDIA/spark-rapids/issues/8017
- [ ] https://github.com/NVIDIA/spark-rapids/issues/8018
- [ ] https://github.com/NVIDIA/spark-rapids/issues/8019
```

```[tasklist]
```

**Comment by HaoYang670** [comment]
Let's try the new `Tasks` feature in GitHub.
