### ISSUE TITLE
[FEA] Avoid memory over usage on GPU nodes in the SparkPlan

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#7252]
**Is your feature request related to a problem? Please describe.**
The goal of this epic is to provide a framework and update a few SparkPlan nodes so that they can intelligently retry tasks when OOM failures are encountered.

- [x] https://github.com/NVIDIA/spark-rapids/issues/7253
- [x] https://github.com/NVIDIA/spark-rapids/issues/7256
- [x] https://github.com/NVIDIA/spark-rapids/issues/7254
- [x] https://github.com/NVIDIA/spark-rapids/issues/7777
- [x] https://github.com/NVIDIA/spark-rapids/issues/7255
- [x] https://github.com/NVIDIA/spark-rapids/issues/7341
- [x] https://github.com/NVIDIA/spark-rapids/issues/7813

**Comment by tgravescs** [comment]
do we want to add https://github.com/NVIDIA/spark-rapids/issues/7934 to this?

**Comment by ttnghia** [comment]
Should we consider adding retry for Parquet writer into this too?

**Comment by revans2** [comment]
@ttnghia this epic is closed. It was a bit of a dumping ground for issues, and I wanted to clean it up. #8029 has parquet writes it.
