### ISSUE TITLE
[FEA] Avoid going over memory and size limitations in GpuExpression evaluation

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#7257]
**Is your feature request related to a problem? Please describe.**
This is related to https://github.com/NVIDIA/spark-rapids/issues/7252 but tries to tackle the problem of Expressions instead of SparkPlan exec nodes. A lot of this is really only needed for cases when we need to split the input batch into multiple output batches. This can happen, but in practice is not that common.

- [ ] https://github.com/NVIDIA/spark-rapids/issues/7258
- [ ] https://github.com/NVIDIA/spark-rapids/issues/7259
- [x] https://github.com/NVIDIA/spark-rapids/issues/7260
- [ ] https://github.com/NVIDIA/spark-rapids/issues/7261
- [ ] File follow on issues to update all existing expressions to use the new framework and add in scale tests for the expressions to be sure that the memory budget is honored.
- [ ] File a follow on issue to understand how to deal with UDFs and how to expose APIs for it publicly.
