### ISSUE TITLE
[FEA] Release Spark 3.4 Support

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#8079]
This is to track progress towards release full Spark 3.4 support in spark-rapids. Issues referenced here are blockers towards a full release of the Spark 3.4 shim. 

### Current Blockers ###

- [x] https://github.com/NVIDIA/spark-rapids/issues/8117

- [x] https://github.com/NVIDIA/spark-rapids/issues/6987

- [x] https://github.com/NVIDIA/spark-rapids/issues/6991

**CI updates**

- [x] https://github.com/NVIDIA/spark-rapids/issues/5824

**Comment by NVnavkumar** [comment]
All Spark 3.4 P0 issues targeting 23.06 have been completed. So we can officially close this issue now.
