### ISSUE TITLE
[FEA] Support conv function

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#8511]
It would be better to support [conv](https://spark.apache.org/docs/latest/api/sql/index.html#conv) function:
Codes:
```
df = spark.createDataFrame([("010101",)], ['n'])
df.select(conv(df.n, 2, 16).alias('hex')).collect()
```
driverlogs:
```
@Expression <Alias> conv(n#0, 2, 16) AS hex#2 could run on GPU
    ! <Conv> conv(n#0, 2, 16) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.Conv
      @Expression <AttributeReference> n#0 could run on GPU
```

## Tasks
 
- [x] JNI API and POC for 10,16 <-> 10, 16 NVIDIA/spark-rapids-jni#1314
- [x] GPUOverrides #8925 
- [ ] Dedicated kernel implementation NVIDIA/spark-rapids-jni#1346
- [ ] Remove restriction to 10<->16, and enable by default

**Comment by mattahrens** [comment]
Scope would include new JNI kernel

**Comment by gerashegalov** [comment]
This can be implemented using a generalized version of [`hex_to_integers`](https://docs.rapids.ai/api/libcudf/stable/group__strings__convert.html#ga31c8d3b529c9a7d00a1b00dd55e537c6) followed by [`integers_to_hex`](https://docs.rapids.ai/api/libcudf/stable/group__strings__convert.html#gacfaa40a6fd38d6d82ca3a15eaef58448) where the radices are not hard-coded to base
