### ISSUE TITLE
[FEA] Hudi table support needed on Spark RAPIDS

### ISSUE THREAD

**Issue by prashantmishrawalmart** [NVIDIA/spark-rapids#8614]
**Is your feature request related to a problem? Please describe.**
The feature request is related to the integration of Hudi (Apache Hudi) with Spark Rapids. Currently, Hudi is not supported in Spark Rapids, and I would like to request the addition of this feature.

**Describe the solution you'd like**
Hudi table read and write support is need on Spark RAPIDS

- [ ] Hudi table read operation (spark DF and spark sql read )
- [ ] Hudi table optimised writes operation (spark DF and spark sql write)
- [ ] MERGE INTO table feature for Hudi
- [ ] Append command feature for Hudi
- [ ] Delete command feature for Hudi
- [ ] Update command feature in Hudi
- [ ] Overwrite command feature in Hudi
- [ ] Hudi table auto compaction
