### ISSUE TITLE
[TEST] Compatibility tests for data formats

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#8666]
Here is a list of tests to confirm data format compatibility with Apache Spark, in the Spark RAPIDS plugin. This list is a work in progress:

- [ ] Test SPARK-10177](https://issues.apache.org/jira/browse/SPARK-10177): Timestamps read incorrectly. Refer to the test in `ParquetHiveCompatibility.scala#L97`
- [ ] Test Parquet reads with `CONVERT_METASTORE_PARQUET_WITH_SCHEMA_MERGING=true`
- [ ] Test Parquet reads for `LIST<STRUCT<int, string>>`: (Refer to https://github.com/rapidsai/cudf/issues/13664)
- [ ] Test [SPARK-16344](https://issues.apache.org/jira/browse/SPARK-16344): `ARRAY<STRUCT<array_element: INT>>`. Refer to test in `ParquetHiveCompatibility.scala#139`
- [ ] Test CPU fallback for user-defined types in ORC read/write: OrcQuerySuite.scala#L108
- [ ] Test ORC reads at scale with all null values: Like OrcQuerySuite.scala#L173, but with large number of rows.
- [ ] Test [SPARK-16610](https://issues.apache.org/jira/browse/SPARK-16610): Honour `orc.compress` on writes, when `compress` is unset: OrcQuerySuite.scala#L189.
- [ ] Test that `compress` is honoured when set (ZLIB, Snappy, None). OrcQuerySuite.scala#L224
- [ ] Test [SPARK-5309](https://issues.apache.org/jira/browse/SPARK-5309): ORC STRING column uses dictionary compression. OrcQuerySuite.scala#359 (Note: Not sure how this test is verifying dictionary_v2).
- [ ] Test [SPARK-9170](https://issues.apache.org/jira/browse/SPARK-9170): Upper case ORC column names are not implicitly stored in lowercase. (OrcQuerySuite.scala:371)

**Comment by mythrocks** [comment]
This task description is unreadable now. 

When I first filed the task, the description had links to reference JIRAs, source code, and a readable text-description for each.

I am supportive of shortening the text, and moving some details to the sub-tasks. But what is someone new to make of #8708?

**Comment by mythrocks** [comment]
Argh. Ignore the previous comment. The task descriptions are rendered unreadable if not logged in through Github Enterprise.

Sorry for the confusion.
