### ISSUE TITLE
[FEA] Create spark 3.5.1 shim and build env

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#9258]
**Is your feature request related to a problem? Please describe.**
Spark 3.5.0 is released, we need to add 3.5.1 snapshot shim and build env

The following issues are related to this Epic 

- [x] https://github.com/NVIDIA/spark-rapids/issues/9875
- [x] https://github.com/NVIDIA/spark-rapids/issues/9859
- [x] https://github.com/NVIDIA/spark-rapids/issues/9743
- [x] https://github.com/NVIDIA/spark-rapids/issues/9472
- [x] https://github.com/NVIDIA/spark-rapids/issues/10028
