### ISSUE TITLE
[FEA] Create Spark 4.0.0 shim and build env

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#9259]
**Is your feature request related to a problem? Please describe.**
Spark 4.0 will be the next major release, create a shim and build env for it.

Note: Need to enable both Scala 2.12 and 2.13

```[tasklist]
### Tasks
- [x] Add support for the internal repo.
- [x] Add support for the external repo.
```

```[tasklist]
### Compilation failures
- [x] https://github.com/NVIDIA/spark-rapids/issues/10669
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10673
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10710
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10711
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10712
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10299
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10714
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10713
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10606
- [ ] https://github.com/NVIDIA/spark-rapids/pull/10828
- [ ] https://github.com/NVIDIA/spark-rapids/pull/10829
- [ ] https://github.com/NVIDIA/spark-rapids/pull/10830
- [ ] https://github.com/NVIDIA/spark-rapids/issues/10972
- [ ] https://github.com/NVIDIA/spark-rapids/issues/11136
```
