### ISSUE TITLE
[FEA] Remove Pascal support

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#9692]
**Is your feature request related to a problem? Please describe.**
RAPIDS will drop support for the Pascal architecture GPU in 24.02.  The RAPIDS Spark team will drop support for Pascal as well.  

**Describe the solution you'd like**
* Remove any Pascal specific tests
* Remove the Pascal build pipeline
* Update documentation to note support for Pascal only in 23.12 and prior. 

**Describe alternatives you've considered**
N/A

**Additional context**
https://docs.rapids.ai/notices/rsn0034/

```[tasklist]
### Tasks
- [X] <del>Update the code to support Volta instead of Pascal</del> (No change required)
- [X] Stop Pascal related build & test pipelines @pxLi 
- [ ] Update the download page to remove P100 and change Pascal to Volta when releasing. @nvliyuan 
```

**Comment by GaryShen2008** [comment]
I searched in the code and didn't find any code commented with Pascal.
The only place in GpuColumnarToRowExec. isAcceleratedTransposeSupported has already checked as Cuda.getComputeCapabilityMajor > 6, which means above Pascal.
So, it may be no necessary to change any code.

**Comment by nvliyuan** [comment]
CC @SurajAralihalli

**Comment by sameerz** [comment]
> The only place in GpuColumnarToRowExec. isAcceleratedTransposeSupported has already checked as Cuda.getComputeCapabilityMajor > 6, which means above Pascal.
So, it may be no necessary to change any code.

Are there any other places in the code where we check whether the user is running on a supported GPU?

**Comment by GaryShen2008** [comment]
Remove myself since it only needs to update doc.

**Comment by nvliyuan** [comment]
close this issue since [pr](https://github.com/NVIDIA/spark-rapids/pull/9943#issuecomment-1838045003) merged
